server:
  port: 9011
spring:
  application:
    name: sales-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/sales_db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password:
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone:
        http://localhost:8761/eureka

swagger:
  title: SaLE SERVICE
  description: This page lists all the rest apis for SALES APP.
  version: 0.0.1
  contact-name: Amine BOUAGGAD
  contact-url: www.omnidata.ma
  contact-email: abouaggad@omnidata.ma
